<div class="index_forms_wrapper clearfix">
	<div class="form_wrapper auth_form_wrapper">
		<form class="index_form" method="post" name="auth" action="/auth">
			<div class="form_title">Authorisation:</div>
			<div class="index_form_str">
				<input class="index_form_field" type="text" name="login" placeholder="Login" required>
			</div>
			<div class="index_form_str">
				<input class="index_form_field" type="password" name="password" placeholder="Password" required>
			</div>
			<div class="index_form_str">
				<input class="index_form_submit" type="submit" name="submit" value="Login">
			</div>
		</form>
	</div>
	<div class="form_wrapper reg_form_wrapper">
		<form class="index_form" method="post" name="auth">
			<div class="form_title">Registration:</div>
			<div class="index_form_str">
				<input class="index_form_field" type="text" name="name" placeholder="First name" required>
			</div>
			<div class="index_form_str">
				<input class="index_form_field" type="text" name="name2" placeholder="Last name" required>
			</div>
			<div class="index_form_str">
				<input class="index_form_field" type="email" name="email" placeholder="Login (e-mail)" required>
			</div>
			<div class="index_form_str">
				<input class="index_form_field" type="password" name="password" placeholder="Password" required>
			</div>
			<div class="index_form_str">
				<input class="index_form_field" type="password" name="password2" placeholder="Confirm password" required>
			</div>
			<div class="index_form_str">
				<input class="index_form_submit" type="submit" name="submit" value="Registration">
			</div>
		</form>
	</div>
</div>