<div class="profile_content">
	<div class="title_gifts">Jackpots:</div>
	<div class="gifts_wrapper">
		<div class="gifts_list clearfix">
			<div class="gift_item">
				<div class="count">1</div>
				<div class="gift_item_img_wr">
					<img class="gift_img" src="img/gift2.png" alt="" title="">
				</div>
				<div class="gift_item_name">House</div>
			</div>
			<div class="gift_item">
				<div class="count">10</div>
				<div class="gift_item_img_wr">
					<img class="gift_img" src="img/gift1.png" alt="" title="">
				</div>
				<div class="gift_item_name">Car</div>
			</div>
			<div class="gift_item">
				<div class="count">50</div>
				<div class="gift_item_img_wr">
					<img class="gift_img" src="img/gift3.png" alt="" title="">
				</div>
				<div class="gift_item_name">Smartphone</div>
			</div>
			<div class="gift_item">
				<div class="count">100</div>
				<div class="gift_item_img_wr">
					<img class="gift_img" src="img/gift4.png" alt="" title="">
				</div>
				<div class="gift_item_name">Kick scooter</div>
			</div>
		</div>
	</div>
	<div class="profile_info_wrapper">
		<div class="profile_info_str clearfix">
			<div class="profile_info_left">Total jackpot money:</div>
			<div class="profile_info_right">1000000 Kč</div>
		</div>
	</div>
	<div class="profile_line"></div>
	<div class="get_gift_wrapper">
		<a class="get_gift_btn" href="">Get prize</a>
	</div>
	<div class="title_gifts"><?= $login ?> prizes:</div>
	<div class="gifts_wrapper">
		<div class="gifts_list clearfix">
			<div class="gift_item">
				<div class="count">0</div>
				<div class="gift_item_img_wr">
					<img class="gift_img" src="img/gift2.png" alt="" title="">
				</div>
				<div class="gift_item_name">House</div>
			</div>
			<div class="gift_item">
				<div class="count">0</div>
				<div class="gift_item_img_wr">
					<img class="gift_img" src="img/gift1.png" alt="" title="">
				</div>
				<div class="gift_item_name">Car</div>
			</div>
			<div class="gift_item">
				<div class="count">0</div>
				<div class="gift_item_img_wr">
					<img class="gift_img" src="img/gift3.png" alt="" title="">
				</div>
				<div class="gift_item_name">Smartphone</div>
			</div>
			<div class="gift_item">
				<div class="count">0</div>
				<div class="gift_item_img_wr">
					<img class="gift_img" src="img/gift4.png" alt="" title="">
				</div>
				<div class="gift_item_name">Kick scooter</div>
			</div>
		</div>
	</div>
	<div class="profile_info_wrapper">
		<div class="profile_info_str clearfix">
			<div class="profile_info_left"><?= $login ?> balance:</div>
			<div class="profile_info_right"><?= $userMoney ?> Kč</div>
		</div>
		<div class="profile_info_str clearfix">
			<div class="profile_info_left"><?= $login ?> balance:</div>
			<div class="profile_info_right"><?= $userBonusBalls ?> bonus balls</div>
		</div>
	</div>
</div>