<?php
    $viewContainer = $_SESSION['viewContainer'];
?>
<div class="profile_content">
	<div class="title_gifts">Jackpots:</div>
	<div class="gifts_wrapper">
		<div class="gifts_list clearfix casino">
            <?php foreach ($viewContainer['casino']['prizes'] as $key => $prize) : ?>
			<div class="gift_item casino">
				<div class="amount <?= $key ?>"><?= $prize['amount'] ?></div>
				<div class="gift_item_img_wr">
					<img class="gift_img" src="<?= $prize['img'] ?>" alt="" title="">
				</div>
				<div class="gift_item_name"><?= $prize['name'] ?></div>
			</div>
            <?php endforeach; ?>
		</div>
	</div>
	<div class="profile_info_wrapper">
		<div class="profile_info_str clearfix">
			<div class="profile_info_left">Total jackpot money:</div>
			<div class="profile_info_right casino_jackpot"><?= $viewContainer['casino']['money'] ?> Kč</div>
		</div>
	</div>
    <div class="profile_line"></div>
	<div class="title_gifts"><?= ucfirst($viewContainer['user']['login']) ?> prizes:</div>
	<div class="gifts_wrapper">
		<div class="gifts_list clearfix user">
            <?php foreach ($viewContainer['user']['prizes'] as $key => $prize) : ?>
                <div class="gift_item">
                    <div class="amount <?= $key ?>"><?= $prize['amount'] ?></div>
                    <div class="gift_item_img_wr">
                        <img class="gift_img" src="<?= $prize['img'] ?>" alt="" title="">
                    </div>
                    <div class="gift_item_name"><?= $prize['name'] ?></div>
                </div>
            <?php endforeach; ?>
		</div>
	</div>
	<div class="profile_info_wrapper">
		<div class="profile_info_str clearfix">
			<div class="profile_info_left"><?= ucfirst($viewContainer['user']['login']) ?> balance:</div>
			<div class="profile_info_right user_money"><?= $viewContainer['user']['money'] ?> Kč</div>
		</div>
		<div class="profile_info_str clearfix">
			<div class="profile_info_left"><?= ucfirst($viewContainer['user']['login']) ?> balance:</div>
			<div class="profile_info_right user_bonus_balls"><?= $viewContainer['user']['bonus_balls'] ?> bonus points</div>
		</div>
	</div>
    <div class="get_gift_wrapper">
        <a class="get_gift_btn" id="get_prize">Get prize</a>
    </div>
		<div class="modal_wnd_wrapper unconfirmed_prize" data-modalstate="<?php echo isset($viewContainer['user']['unconfirmed_prize']['id']) ? 'open': 'hidden';?>">
			<div class="modal_wnd">
				<?php
					$prizes = [
						0 => [
							'img' => 'img/gift2.png'
						],
						1 => [
							'img' => 'img/gift1.png'
						],
						2 => [
							'img' => 'img/gift3.png'
						],
						3 => [
							'img' => 'img/gift4.png'
						],
					];
				?>
				<h3>You have unconfirmed prizes!</h3>
				<p>Congratulations! You won the <span class="unconfirmed_prize"><?= $viewContainer['user']['unconfirmed_prize']['name'] ?></span>! Do you want us to send it to you? Also you can change it to bonuse points - <span class="prize_to_bonuses"><?= $viewContainer['user']['prize_to_bonuses'] ?></span>.</p>
				<div class="modal_wnd_img"><img src="<?= $prizes[$viewContainer['user']['unconfirmed_prize']['id']]['img'] ?>" alt="<?= $viewContainer['user']['unconfirmed_prize']['name'] ?>"></div>
				<div class="btn_wrapper"><a class="get_gift_btn" id="send_prize">YES!</a><a class="get_gift_btn" id="reject_prize">No, thanks.</a></div>
			</div>
		</div>
		<div class="modal_wnd_wrapper unconfirmed_money" data-modalstate="<?= $viewContainer['user']['unconfirmed_money'] ? 'open': 'hidden';?>">
			<div class="modal_wnd">
				<h3>You have unconfirmed prizes!</h3>
				<p>Congratulations! You won <span class="unconfirmed_money"><?= $viewContainer['user']['unconfirmed_money'] ?></span> Kč! Do you want get it in your bank account? Also you can change it to bonuse points - <span class="money_to_bonuses"><?= $viewContainer['user']['money_to_bonuses'] ?></span>.</p>
				<div class="btn_wrapper"><a class="get_gift_btn" id="sendMoneyToBank">YES!</a><a class="get_gift_btn" id="get_bonuses">No, get bonus points.</a></div>
			</div>
		</div>
</div>