<?php
    $viewContainer = $_SESSION['viewContainer'];
?>
<div class="profile_content">
	<div class="title_gifts">Jackpots:</div>
	<div class="gifts_wrapper">
		<div class="gifts_list clearfix">
            <?php foreach ($viewContainer['casino']['prizes'] as $prize) : ?>
			<div class="gift_item">
				<div class="count"><?= $prize['amount'] ?></div>
				<div class="gift_item_img_wr">
					<img class="gift_img" src="<?= $prize['img'] ?>" alt="" title="">
				</div>
				<div class="gift_item_name"><?= $prize['name'] ?></div>
			</div>
            <?php endforeach; ?>
		</div>
	</div>
	<div class="profile_info_wrapper">
		<div class="profile_info_str clearfix">
			<div class="profile_info_left">Total jackpot money:</div>
			<div class="profile_info_right"><?= $viewContainer['casino']['money'] ?> Kč</div>
		</div>
	</div>
    <div class="profile_line"></div>
	<div class="title_gifts"><?= ucfirst($viewContainer['user']['login']) ?> prizes:</div>
	<div class="gifts_wrapper">
		<div class="gifts_list clearfix">
            <?php foreach ($viewContainer['user']['prizes'] as $prize) : ?>
                <div class="gift_item">
                    <div class="count"><?= $prize['amount'] ?></div>
                    <div class="gift_item_img_wr">
                        <img class="gift_img" src="<?= $prize['img'] ?>" alt="" title="">
                    </div>
                    <div class="gift_item_name"><?= $prize['name'] ?></div>
                </div>
            <?php endforeach; ?>
		</div>
	</div>
	<div class="profile_info_wrapper">
		<div class="profile_info_str clearfix">
			<div class="profile_info_left"><?= ucfirst($viewContainer['user']['login']) ?> balance:</div>
			<div class="profile_info_right"><?= $viewContainer['user']['money'] ?> Kč</div>
		</div>
		<div class="profile_info_str clearfix">
			<div class="profile_info_left"><?= ucfirst($viewContainer['user']['login']) ?> balance:</div>
			<div class="profile_info_right"><?= $viewContainer['user']['bonus_balls'] ?> bonus balls</div>
		</div>
	</div>
    <div class="get_gift_wrapper">
        <a class="get_gift_btn" id="get_prize">Get prize</a>
    </div>
    <?php if ($viewContainer['user']['unconfirmed_prize']) : ?>
    <div class="modal_wnd_wrapper">
        <div class="modal_wnd">
            <h3>You have unconfirmed prizes!</h3>
            <p>Congratulations! You won the <?= $viewContainer['user']['unconfirmed_prize'] ?>! Do you want us to send it to you?</p>
            <div class="btn_wrapper"><a class="get_gift_btn" href="/">YES!</a><a class="get_gift_btn" href="">No, thanks.</a></div>
        </div>
    </div>
    <?php endif; ?>
</div>